//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Data.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_DATA_H)
#define _DATA_H


class Data {
private:
	int dzien;
	int miesiac;
	int rok;
	int godzina;
	int minuta;
	int sekunda;
};

#endif  //_DATA_H
