//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Data.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_DATA_H)
#define _DATA_H

#include <string>
#include <ctime>
#include <iostream>
#include <sstream>

class Data {
private:
	int dzien;
	int miesiac;
	int rok;
	int godzina = 0;
	int minuta = 0;
	int sekunda = 0;
public:
	Data();
	Data(int d, int m, int r);
	Data(int d, int m, int r, int g, int mi, int s);
	Data(std::string data);
	static std::string dzis_string();
	static Data dzis();
	static std::string data_na_string(Data d);
	std::string string();
	Data operator+(int dni) const;
	Data operator-(int dni) const;
	~Data() = default;
};

#endif  //_DATA_H
