//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : DodatkowaUsluga.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_DODATKOWAUSLUGA_H)
#define _DODATKOWAUSLUGA_H

#include <string>

class DodatkowaUsluga {
private:
	std::string nazwa;
	double cena;
public:
	DodatkowaUsluga();
	DodatkowaUsluga(std::string nazwa, double cena);
	~DodatkowaUsluga() = default;
	std::string linia();
	std::string opis();
};

#endif  //_DODATKOWAUSLUGA_H
