//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Gosc.cpp
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#define STRZALKI -32
#define GORA 72
#define DOL 80
#define ESC 27
#define ENTER 13



#include "Gosc.h"

Gosc::Gosc() {}

void Gosc::przegladaj_katalog() 
{
    system("cls");
	auto katalog = std::dynamic_pointer_cast<KatalogDlaGosci>(Katalog::pobierzInstancje());
    bool rysuj = true;
    int wybor = 0;
    int start = 0;
    int ilosc = 10;
    int stop = min(start + ilosc, katalog->get_ilosc_pokoi());
    while (true)
    {
        if (rysuj)
        {
            std::cout << "\033[" << 0 << ";" << 0 << "H";
            std::cout << "ESC - wyjscie z katlogu\n";
            std::cout << "F - wybierz filtry\n";
            std::cout << "ENTER - wybierz pokoj do rezerwacji\n\n";
            for (int i = start; i < stop; i++)
            {
                std::cout << i << ". " << (wybor == i ? "\033[38;5;0;48;5;15m" : "") << katalog->get_opis(i) << "\x1b[0m          \n";
            }
            rysuj = false;
        }
        char klawisz = Ekran::klawisz(); //przeniesc wywolanie funkcji do switch
        switch (klawisz) 
        {
        case STRZALKI:
        {
            switch (Ekran::klawisz())
            {
            case GORA:
            {
                if (wybor)
                {
                    wybor--;
                    rysuj = true;
                    if (wybor-start < 2)
                    {
                        if (start > 0)
                        {
                            start--;
                            stop--;
                        }
                    }
                }
                break;
            }
            case DOL:
            {
                if (wybor < katalog->get_ilosc_pokoi()-3)
                {
                    wybor++;
                    rysuj = true;
                    if (stop-wybor < 2)  
                    {
                        if (stop < katalog->get_ilosc_pokoi() - 2)
                        {
                            start++;
                            stop++;
                        }
                    }
                }
                break;
            }
            default:
                break;
            }
            break;
        }
        case ESC:
        {
            system("cls");
            return;
        }
        case ENTER:
        {
            //tu bêdzie rezerwowanie
            break;
        }
        case 'F':
        {
            break;
        }
        default:
            if (klawisz != 0)
                std::cout << "Nieznany klawisz: " << (int)klawisz << std::endl; //usun¹æ
            break;
        }

        //Ó -32
        //H 72 - góra
        //Ó - 32
        //P 80 -dó³
    }
}

void Gosc::przegladaj_historie_rezerwacji() 
{

}


std::vector<std::shared_ptr<Pokoj>> polacz_wyniki_filtrow(std::vector<std::shared_ptr<Pokoj>> v1, std::vector<std::shared_ptr<Pokoj>> v2)
{
    std::vector<std::shared_ptr<Pokoj>> wynik;

    for (const auto& p1 : v1) 
    {
        for (const auto& p2 : v2) 
        {
            if (p1 == p2) // porównanie wskaŸników, czyli ten sam obiekt
            { 
                wynik.push_back(p1);
                break; // wystarczy jeden raz
            }
        }
    }
    return wynik;
}

void Gosc::gui() {
    
    system("cls");
    //system("clear");
    int a;
    do {
        std::cout << "1. Pokaz katalog.\n2. Pokaz historie rezerwacji.\n3. Wyloguj sie.\n";
        std::cin >> a;
        if (std::cin.fail()) {
            std::cin.clear();
            std::cin.ignore(1000, '\n');
        }
        if (a == 1) {
            przegladaj_katalog();
        }
        if (a == 2) {
            przegladaj_historie_rezerwacji();
        }
        if (a == 3) {
            wyloguj();
            break;
        }
    } while (true);
}

