//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Gosc.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_GOSC_H)
#define _GOSC_H

#include "Uzytkownik.h"

class Gosc : public Uzytkownik {
public:
	void przegladaj_katalog();
	void przegladaj_historie_rezerwacji();
private:
	collection<Rezerwacja> historia_rezervacji;
};

#endif  //_GOSC_H
