//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Gosc.cpp
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#include "Gosc.h"

void Gosc::przegladaj_katalog() {

}

void Gosc::przegladaj_historie_rezerwacji() {

}

