//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KatalogDlaPracownikow.cpp
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#include "KatalogDlaPracownikow.h"
#include "Data.h"

void KatalogDlaPracownikow::dodaj_pokoj() {

}

void KatalogDlaPracownikow::edytuj_pokoj() {

}

void KatalogDlaPracownikow::usun_pokoj() {

}

void KatalogDlaPracownikow::filtruj_wg_daty(Data data) {

}

void KatalogDlaPracownikow::filtruj_wg_ceny(double min, double max) {

}

void KatalogDlaPracownikow::filtruj_wg_ilosci_osob(int ilosc) {

}

void KatalogDlaPracownikow::filtruj_wg_standardu() {

}

void KatalogDlaPracownikow::dodaj_usluge() {

}

void KatalogDlaPracownikow::edytuj_usluge() {

}

void KatalogDlaPracownikow::usun_usluge() {

}

