//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KatalogDlaPracownikow.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_KATALOGDLAPRACOWNIKOW_H)
#define _KATALOGDLAPRACOWNIKOW_H

#include "Data.h"

class KatalogDlaPracownikow {
public:
	void dodaj_pokoj();
	void edytuj_pokoj();
	void usun_pokoj();
	void filtruj_wg_daty(Data data);
	void filtruj_wg_ceny(double min, double max);
	void filtruj_wg_ilosci_osob(int ilosc);
	void filtruj_wg_standardu();
	void dodaj_usluge();
	void edytuj_usluge();
	void usun_usluge();
};

#endif  //_KATALOGDLAPRACOWNIKOW_H
