//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KatalogDlaGosci.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_KATALOGDLAGOSCI_H)
#define _KATALOGDLAGOSCI_H

#include "Data.h"
#include "Rezerwacja.h"

class KatalogDlaGosci {
public:
	virtual std::vector<std::shared_ptr<Pokoj>> filtruj_wg_daty(Data data) = 0;
	virtual std::vector<std::shared_ptr<Pokoj>> filtruj_wg_ceny(double min, double max) = 0;
	virtual std::vector<std::shared_ptr<Pokoj>> filtruj_wg_ilosci_osob(int ilosc) = 0;
	virtual std::vector<std::shared_ptr<Pokoj>> filtruj_wg_standardu() = 0;
	virtual Rezerwacja zarezerwuj() = 0;
	virtual ~KatalogDlaGosci() = default;

	virtual int get_ilosc_pokoi() = 0;
	virtual std::string get_opis(int indeks) = 0;
};

#endif  //_KATALOGDLAGOSCI_H
