//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Katalog.cpp
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#include "Katalog.h"
#include "Data.h"
#include "Rezerwacja.h"

Katalog::Katalog()
{

}

std::shared_ptr<Katalog> Katalog::pobierzInstancje() {
    static std::shared_ptr<Katalog> instancja(new Katalog());
    return instancja;
}

std::vector<std::shared_ptr<Pokoj>> Katalog::filtruj_wg_daty(Data data)
{
    return std::vector<std::shared_ptr<Pokoj>>();
}

std::vector<std::shared_ptr<Pokoj>> Katalog::filtruj_wg_ceny(double min, double max)
{
    return std::vector<std::shared_ptr<Pokoj>>();
}

std::vector<std::shared_ptr<Pokoj>> Katalog::filtruj_wg_ilosci_osob(int ilosc)
{
    return std::vector<std::shared_ptr<Pokoj>>();
}

std::vector<std::shared_ptr<Pokoj>> Katalog::filtruj_wg_standardu()
{
    return std::vector<std::shared_ptr<Pokoj>>();
}

Rezerwacja Katalog::zarezerwuj() 
{
	return Rezerwacja();
}

void Katalog::dodaj_pokoj() 
{

}

void Katalog::edytuj_pokoj() 
{

}

void Katalog::usun_pokoj() 
{

}

void Katalog::dodaj_usluge() 
{

}

void Katalog::edytuj_usluge() 
{

}

void Katalog::usun_usluge() 
{

}

