//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Katalog.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_KATALOG_H)
#define _KATALOG_H

#include <vector>
#include <memory>
#include "KatalogDlaGosci.h"
#include "KatalogDlaPracownikow.h"
#include "Data.h"
#include "Rezerwacja.h"
#include "Pokoj.h"
#include "DodatkowaUsluga.h"

class Katalog : public KatalogDlaGosci, public KatalogDlaPracownikow {
private:
	std::vector<Pokoj> pokoje;
	std::vector<DodatkowaUsluga> uslugi;
	
	Katalog();

	Katalog(const Katalog&) = delete;
	Katalog& operator=(const Katalog&) = delete;

public:
	~Katalog() = default;

	static std::shared_ptr<Katalog> pobierzInstancje();

	std::vector<std::shared_ptr<Pokoj>> filtruj_wg_daty(Data data) override;
	std::vector<std::shared_ptr<Pokoj>> filtruj_wg_ceny(double min, double max) override;
	std::vector<std::shared_ptr<Pokoj>> filtruj_wg_ilosci_osob(int ilosc) override;
	std::vector<std::shared_ptr<Pokoj>> filtruj_wg_standardu() override;
	Rezerwacja zarezerwuj() override;
	void dodaj_pokoj() override;
	void edytuj_pokoj() override;
	void usun_pokoj() override;
	void dodaj_usluge() override;
	void edytuj_usluge() override;
	void usun_usluge() override;
};

#endif  //_KATALOG_H
