//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KatalogDlaGosci.cpp
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#include "KatalogDlaGosci.h"
#include "Data.h"
#include "Rezerwacja.h"

void KatalogDlaGosci::filtruj_wg_daty(Data data) {

}

void KatalogDlaGosci::filtruj_wg_ceny(double min, double max) {

}

void KatalogDlaGosci::filtruj_wg_ilosci_osob(int ilosc) {

}

void KatalogDlaGosci::filtruj_wg_standardu() {

}

Rezerwacja KatalogDlaGosci::zarezerwuj() {
	return Rezerwacja();
}

