//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KatalogDlaPracownikow.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_KATALOGDLAPRACOWNIKOW_H)
#define _KATALOGDLAPRACOWNIKOW_H

#include "Data.h"

class KatalogDlaPracownikow {
public:
	virtual void dodaj_pokoj() = 0;
	virtual void edytuj_pokoj() = 0;
	virtual void usun_pokoj() = 0;
	virtual std::vector<short> filtruj_wg_daty(Data data) = 0;
	virtual std::vector<short> filtruj_wg_ceny(double min, double max) = 0;
	virtual std::vector<short> filtruj_wg_ilosci_osob(int ilosc) = 0;
	virtual std::vector<short> filtruj_wg_standardu(std::string standard) = 0;
	virtual void dodaj_usluge() = 0;
	virtual void edytuj_usluge() = 0;
	virtual void usun_usluge() = 0;
	virtual ~KatalogDlaPracownikow() = default;
};

#endif  //_KATALOGDLAPRACOWNIKOW_H
