//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KatalogDlaGosci.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_KATALOGDLAGOSCI_H)
#define _KATALOGDLAGOSCI_H

#include "Data.h"
#include "Rezerwacja.h"

class KatalogDlaGosci {
public:
	void filtruj_wg_daty(Data data);
	void filtruj_wg_ceny(double min, double max);
	void filtruj_wg_ilosci_osob(int ilosc);
	void filtruj_wg_standardu();
	Rezerwacja zarezerwuj();
};

#endif  //_KATALOGDLAGOSCI_H
