//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Katalog.cpp
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#include "Katalog.h"
#include "Data.h"
#include "Rezerwacja.h"

Katalog::Katalog()
{
    wczytaj_pokoje();
    wczytaj_uslugi();
}

DodatkowaUsluga parse_csv_uslugi(std::string& linia) {
    std::stringstream ss(linia);
    std::string token;

    std::getline(ss, token, ',');
    std::string nazwa = token;

    std::getline(ss, token, ',');
    int cena = stoi(token);

    return DodatkowaUsluga(nazwa, cena);
}

std::shared_ptr<Pokoj> parse_csv_pokoj(std::string& linia) {
    std::stringstream ss(linia);
    std::string token;

    std::getline(ss, token, ',');
    int numer = stoi(token);

    std::getline(ss, token, ',');
    int maks_liczba_os = stoi(token);

    std::getline(ss, token, ',');
    double cena_noc = stod(token);

    std::getline(ss, token, ',');
    std::string standard = token;

    std::shared_ptr<Pokoj> p(new Pokoj(numer, maks_liczba_os, cena_noc, standard));
    return p;

}

void Katalog::wczytaj_pokoje() {
    std::ifstream plik("dane/pokoje.csv");
    std::string linia;
    //std::getline(plik, linia);
    while (std::getline(plik, linia)) {
        this->pokoje.push_back(parse_csv_pokoj(linia));
    }
}

void Katalog::wczytaj_uslugi() {
    std::ifstream plik("dane/uslugi.csv");
    std::string linia;
    //std::getline(plik, linia);
    while (std::getline(plik, linia)) {
        this->uslugi.push_back(parse_csv_uslugi(linia));
    }
}

void Katalog::zapisz_pokoje() {
    std::ofstream p("dane/pokoje.csv", std::ios::out);
    std::string linia;
    for (auto& pokoj : pokoje) {
        linia = pokoj->linia();
        p << linia << "\n";
    }
}

void Katalog::zapisz_uslugi() {
    std::ofstream p("dane/uslugi.csv", std::ios::out);
    std::string linia;
    for (auto& usluga : uslugi) {
        linia = usluga.linia();
        p << linia << "\n";
    }
}

std::shared_ptr<Katalog> Katalog::pobierzInstancje() {
    static std::shared_ptr<Katalog> instancja(new Katalog());
    return instancja;
}

std::shared_ptr<KatalogDlaGosci> KatalogDlaGosci::pobierzInstancjeGosc() {
    return Katalog::pobierzInstancje();
}

std::vector<short> Katalog::filtruj_wg_daty(Data data)
{
    std::vector<short> wyniki;
    for (int i = 0; i < pokoje.size(); i++)
    {
        bool found=false;
        for (auto& d : pokoje[i]->getNiedostepneDaty())
        {
            if (d == data)
            {
                found = true;
            }
        }
        if (!found)
        {
            wyniki.push_back(i);
        }
    }
    return wyniki;
}

std::vector<short> Katalog::filtruj_wg_ceny(double min, double max)
{
    std::vector<short> wyniki;
    for (int i = 0; i < pokoje.size(); i++)
    {
        if(pokoje[i]->getCenaZaNoc() >= min && pokoje[i]->getCenaZaNoc() <= max)
            wyniki.push_back(i);
    }
    return wyniki;
}

std::vector<short> Katalog::filtruj_wg_ilosci_osob(int ilosc)
{
    std::vector<short> wyniki;
    for (int i = 0; i < pokoje.size(); i++)
    {
        if(pokoje[i]->getMaksymalnaLiczbaOsob()>=ilosc)
            wyniki.push_back(i);
    }
    return wyniki;
}

std::vector<short> Katalog::filtruj_wg_standardu(std::string standard)
{
    std::vector<short> wyniki;
    for (int i = 0; i < pokoje.size(); i++)
    {
        if(standard == "all" || pokoje[i]->getStandardPokoju() == standard)
            wyniki.push_back(i);
    }
    return wyniki;
}

Rezerwacja Katalog::zarezerwuj(std::string uzytkownik, Data data_przyjazdu, Data data_wymeldowania, int pokoj, std::vector<short> uslugi, double cena)
{
    std::vector<DodatkowaUsluga> dus;
    for (auto& u : uslugi)
    {
        dus.push_back(this->uslugi[u]);
    }
    Rezerwacja r(uzytkownik, data_przyjazdu, data_wymeldowania, pokoje[pokoj], dus, "do oplacenia", cena, true); //TODO
    pokoje[pokoj]->set_niedostepne(data_przyjazdu, data_wymeldowania);
	return r;
}

void Katalog::dodaj_pokoj() 
{

    zapisz_pokoje();
}

void Katalog::edytuj_pokoj() 
{
    zapisz_pokoje();
}

void Katalog::usun_pokoj() 
{
    zapisz_pokoje();
}

void Katalog::dodaj_usluge() 
{
    zapisz_uslugi();
}

void Katalog::edytuj_usluge() 
{
    zapisz_uslugi();
}

void Katalog::usun_usluge() 
{
    zapisz_uslugi();
}

int Katalog::get_ilosc_pokoi()
{
    return pokoje.size();
}

std::string Katalog::get_opis(int indeks)
{
    if ((indeks < 0) || (indeks > pokoje.size()-1))
    {
        return "error";
    }
    return pokoje[indeks]->opis();
}

int Katalog::get_ilosc_uslug()
{
    return uslugi.size();
}

std::string Katalog::get_opis_uslugi(int indeks)
{
    if ((indeks < 0) || (indeks > uslugi.size() - 1))
    {
        return "error";
    }
    return uslugi[indeks].opis();
}

int Katalog::get_numer(int indeks) {
    return pokoje[indeks]->getNumer();
}

double Katalog::get_cena(int indeks) {
    return pokoje[indeks]->getCenaZaNoc();
}

double Katalog::get_cena_uslugi(int indeks) {
    return uslugi[indeks].get_cena();
}

std::vector<std::shared_ptr<Pokoj>> Katalog::get_vector_pokoi()
{
    return pokoje;
}

std::shared_ptr<Pokoj> Katalog::get_pokoj(int numer)
{
    auto k = Katalog::pobierzInstancje();
    for (auto& p : k->get_vector_pokoi())
    {
        if (numer == p->getNumer())
        {
            return p;
        }
    }
}

void Katalog::przeladuj_pokoje() {
    auto k = Katalog::pobierzInstancje();
    for (auto& p : k->get_vector_pokoi())
    {
        p->przeladuj_pokoj();
    }
}