//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Katalog.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_KATALOG_H)
#define _KATALOG_H

#include <vector>
#include "KatalogDlaGosci.h"
#include "KatalogDlaPracownikow.h"
#include "Data.h"
#include "Rezerwacja.h"
#include "Pokoj.h"
#include "DodatkowaUsluga.h"

class Katalog : public KatalogDlaGosci, public KatalogDlaPracownikow {
public:
	void filtruj_wg_daty(Data data);
	void filtruj_wg_ceny(double min, double max);
	void filtruj_wg_ilosci_osob(int ilosc);
	void filtruj_wg_standardu();
	Rezerwacja zarezerwuj();
	void dodaj_pokoj();
	void edytuj_pokoj();
	void usun_pokoj();
	void dodaj_usluge();
	void edytuj_usluge();
	void usun_usluge();
private:
	std::vector<Pokoj> pokoje;
	std::vector<DodatkowaUsluga> uslugi;
};

#endif  //_KATALOG_H
