//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Platnosc.cpp
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#include "Platnosc.h"

Platnosc::Platnosc()
{

}

void Platnosc::wygeneruj_fakture() 
{

}

