//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Platnosc.cpp
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#include "Platnosc.h"
#include "Wiadomosc.h"

Platnosc::Platnosc(double kwota, std::string platnik, Data data)
{
	this->kwota = kwota;
	this->platnik = platnik;
	this->data = data;
	this->wygeneruj_fakture();
}

void Platnosc::wygeneruj_fakture() 
{
	std::vector<std::string> tresc;
	tresc.push_back("TODO: dodaæ tresc");
	tresc.push_back("kiedys sie to zrobi");
	Wiadomosc("System", platnik, "Potwierdzenie platnosci", tresc, data, true);
}

