//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Platnosc.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_PLATNOSC_H)
#define _PLATNOSC_H

#include "Data.h"

class Platnosc {
private:
	int kwota;
	int status_platnosci;
	Data data;
public:
	Platnosc();
	~Platnosc() = default;
	void wygeneruj_fakture();
};

#endif  //_PLATNOSC_H
