//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Platnosc.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_PLATNOSC_H)
#define _PLATNOSC_H

#include "Data.h"

class Platnosc {
private:
	double kwota;
	std::string platnik;
	Data data;
	void wygeneruj_fakture();
public:
	Platnosc(double kwota, std::string platnik, Data data);
	~Platnosc() = default;
};

#endif  //_PLATNOSC_H
