//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pokoj.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_POKOJ_H)
#define _POKOJ_H

#include <vector>
#include <string>
#include "Data.h"

class Pokoj {
private:
	int numer;
	int maksymalna_liczba_osob;
	int aktualny_status;
	std::vector<Data> niedostepne_daty;
	double cena_za_noc;
	std::string standard_pokoju;
public:
	Pokoj();
	Pokoj(int numer, int maksymalna_liczba_osob, double cena_za_noc, std::string standard_pokoju);
	~Pokoj() = default;
	std::string linia();
	std::string opis();

	int getNumer();
	int getMaksymalnaLiczbaOsob();
	double getCenaZaNoc();
	std::string getStandardPokoju();
	std::vector<Data> getNiedostepneDaty();
	void set_niedostepne(Data d1, Data d2);
};

#endif  //_POKOJ_H
