//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pokoj.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_POKOJ_H)
#define _POKOJ_H

#include <vector>
#include <string>

class Pokoj {
private:
	int numer;
	int maksymalna_liczba_osob;
	int aktualny_status;
	std::vector<Data> niedostepne_daty;
	double cena_za_noc;
	std::string standard_pokoju;
public:
	Pokoj();
	~Pokoj() = default;
};

#endif  //_POKOJ_H
