//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pracownik.cpp
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#include "Pracownik.h"

Pracownik::Pracownik(){}

void Pracownik::aktualizuj_katalog() 
{
	auto katalog = std::dynamic_pointer_cast<KatalogDlaPracownikow>(Katalog::pobierzInstancje());
}

void Pracownik::przegladaj_katalog() 
{

}

void Pracownik::gui() {
	system("cls");
	//system("clear");
    int a;
    do {
        std::cout << "1. Pokaz katalog.\n2. Aktualizuj katalog.\n3. Wyloguj sie.\n";
        std::cin >> a;
        if (std::cin.fail()) {
            std::cin.clear();
            std::cin.ignore(1000, '\n');
        }
        if (a == 1) {
            przegladaj_katalog();
        }
        if (a == 2) {
            aktualizuj_katalog();
        }
        if (a == 3) {
            wyloguj();
            break;
        }
    } while (true);
}

