//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pracownik.cpp
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#include "Pracownik.h"

Pracownik::Pracownik(){}

void Pracownik::aktualizuj_katalog() 
{
	auto katalog = std::dynamic_pointer_cast<KatalogDlaPracownikow>(Katalog::pobierzInstancje());
}

void Pracownik::przegladaj_katalog() 
{

}

void Pracownik::gui() {
	system("cls");
	//system("clear");
	std::cout << "TU BEDZIE GUI\n";
	system("pause");
}

