//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pracownik.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_PRACOWNIK_H)
#define _PRACOWNIK_H

#include "WirtualnaRecepcja.h"
#include "Uzytkownik.h"

class Pracownik : public Uzytkownik {
public:
	void aktualizuj_katalog();
	void przegladaj_katalog();
private:
	WirtualnaRecepcja* recepcja;
};

#endif  //_PRACOWNIK_H
