//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pracownik.cpp
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#include "Pracownik.h"

void Pracownik::aktualizuj_katalog() {

}

void Pracownik::przegladaj_katalog() {

}

