//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pracownik.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_PRACOWNIK_H)
#define _PRACOWNIK_H

#include <memory>
#include "WirtualnaRecepcja.h"
#include "Uzytkownik.h"
#include "Katalog.h"
#include "KatalogDlaPracownikow.h"

class Pracownik : public Uzytkownik {
private:
	std::shared_ptr<WirtualnaRecepcja> recepcja;
public:
	Pracownik();
	~Pracownik() = default;
	void aktualizuj_katalog();
	void przegladaj_katalog();
};

#endif  //_PRACOWNIK_H
