//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Rezerwacja.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_REZERWACJA_H)
#define _REZERWACJA_H

#include <vector>
#include <memory>
#include "Platnosc.h"
#include "Data.h"
#include "DodatkowaUsluga.h"
#include "Pokoj.h"

class Rezerwacja {
private:
	std::string uzytkownik;
	Data data_przyjazdu;
	Data data_wymeldowania;
	int status_rezerwacji;
	int liczba_osob;
	std::vector<DodatkowaUsluga> dodatkowe_uslugi;
	std::shared_ptr<Pokoj> pokoj;
	std::shared_ptr<Platnosc> platnosc;
public:
	Rezerwacja(std::string uzytkownik, Data data_przyjazdu, Data data_wymeldowania, std::shared_ptr<Pokoj> pokoj, std::vector<DodatkowaUsluga> dodatkowe_uslugi, bool nowa = false);
	~Rezerwacja() = default;
	Platnosc zaplac();
	void pokaz_szczegoly();
	void anuluj();
	void zmien_dane();
};

#endif  //_REZERWACJA_H
