//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Rezerwacja.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_REZERWACJA_H)
#define _REZERWACJA_H

#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <fstream>
#include "Platnosc.h"
#include "Data.h"
#include "DodatkowaUsluga.h"
#include "Pokoj.h"


using json = nlohmann::json;

class Rezerwacja {
private:
	int id;
	std::string uzytkownik;
	Data data_przyjazdu;
	Data data_wymeldowania;
	std::string status_rezerwacji;
	int liczba_osob;
	std::vector<DodatkowaUsluga> dodatkowe_uslugi;
	std::shared_ptr<Pokoj> pokoj;
	double cena;
	void dopisz_do_pliku();
	int odczytaj_id_z_pliku();
	void zapisz_id_do_pliku(int id);
	void zmien_status_rezerwacji(std::string status);
public:
	Rezerwacja(std::string uzytkownik, Data data_przyjazdu, Data data_wymeldowania, std::shared_ptr<Pokoj> pokoj, std::vector<DodatkowaUsluga> dodatkowe_uslugi, std::string status_rezerwacji, double cena, bool nowa = false, int id=-1);
	~Rezerwacja() = default;
	Platnosc zaplac();
	void pokaz_szczegoly();
	void anuluj();
	Data get_data_przyjazdu();
	Data get_data_wymeldowania();
	static std::vector<Rezerwacja> odczytaj_rezerwacje(std::string nazwa_uzytkownika);
	static std::vector<Rezerwacja> odczytaj_wszystkie_rezerwacje();
	static std::vector<Data> odczytaj_niedostepne_daty_dla_pokoju(int numer_pokoju);

	std::string getStatusRezerwacji();
	void setStatusRezerwacji(std::string status);
	int get_id();
	std::string get_gosc();
	std::shared_ptr<Pokoj> get_pokoj();
};

#endif  //_REZERWACJA_H
