//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Rezerwacja.cpp
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#include "Rezerwacja.h"
#include "Platnosc.h"

Platnosc Rezerwacja::zaplac() {

}

void Rezerwacja::pokaz_szczegoly() {

}

void Rezerwacja::anuluj() {

}

void Rezerwacja::zmien_dane() {

}

