//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Rezerwacja.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_REZERWACJA_H)
#define _REZERWACJA_H

#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <fstream>
#include "Platnosc.h"
#include "Data.h"
#include "DodatkowaUsluga.h"
#include "Pokoj.h"


using json = nlohmann::json;

class Rezerwacja {
private:
	std::string uzytkownik;
	Data data_przyjazdu;
	Data data_wymeldowania;
	std::string status_rezerwacji;
	int liczba_osob;
	std::vector<DodatkowaUsluga> dodatkowe_uslugi;
	std::shared_ptr<Pokoj> pokoj;
	std::shared_ptr<Platnosc> platnosc;
	void dopisz_do_pliku();
public:
	Rezerwacja(std::string uzytkownik, Data data_przyjazdu, Data data_wymeldowania, std::shared_ptr<Pokoj> pokoj, std::vector<DodatkowaUsluga> dodatkowe_uslugi, std::string status_rezerwacji, bool nowa = false);
	~Rezerwacja() = default;
	Platnosc zaplac();
	void pokaz_szczegoly();
	void anuluj();
	void zmien_dane();
	Data get_data_przyjazdu();
	Data get_data_wymeldowania();
	static std::vector<Rezerwacja> odczytaj_rezerwacje(std::string nazwa_uzytkownika);

};

#endif  //_REZERWACJA_H
