//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_UZYTKOWNIK_H)
#define _UZYTKOWNIK_H

#include <string>
#include <vector>
#include "Wiadomosc.h"

class Uzytkownik {
public:
	void wyslij_wiadomosc();
	void przegladaj_wiadomosci();
	void zaloguj();
	void wyloguj();
	void zarejestruj();
	Uzytkownik();
private:
	std::string login;
	std::string haslo;
	std::vector<Wiadomosc> wyslane_wiadomosci;
	std::vector<Wiadomosc> odebrane_wiadomosci;
};

#endif  //_UZYTKOWNIK_H
