//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.cpp
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#include "Uzytkownik.h"

Uzytkownik::Uzytkownik() {

}

void Uzytkownik::wyslij_wiadomosc() {

}

void Uzytkownik::przegladaj_wiadomosci() {

}

void Uzytkownik::zaloguj() {

}

void Uzytkownik::wyloguj() {

}

void Uzytkownik::zarejestruj() {

}

