//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_UZYTKOWNIK_H)
#define _UZYTKOWNIK_H


class Uzytkownik {
public:
	void wyslij_wiadomosc();
	void przegladaj_wiadomosci();
	void zaloguj();
	void wyloguj();
	void zarejestruj();
private:
	string login;
	string haslo;
	collection<Wiadomosc> wyslane_wiadomosci;
	collection<Wiadomosc> odebrane_wiadomosci;
};

#endif  //_UZYTKOWNIK_H
