//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_UZYTKOWNIK_H)
#define _UZYTKOWNIK_H

#include <string>
#include <vector>
#include <fstream>
#include <iostream>
#include <sstream>
#include <regex>
#include "Wiadomosc.h"


class Uzytkownik {
private:
	std::string login;
	std::string haslo;
	std::vector<Wiadomosc> wyslane_wiadomosci;
	std::vector<Wiadomosc> odebrane_wiadomosci;
public:
	Uzytkownik();
	~Uzytkownik() = default;
	void wyslij_wiadomosc();
	void przegladaj_wiadomosci();
	bool zaloguj(std::string plik);
	void wyloguj();
	void zarejestruj(std::string plik);
	
};

#endif  //_UZYTKOWNIK_H
