//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wiadomosc.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_WIADOMOSC_H)
#define _WIADOMOSC_H

#include <string>
#include "Data.h"
#include "Uzytkownik.h"


class Wiadomosc {
private:
	Uzytkownik* adresat;
	Uzytkownik* nadawca;
	std::string tresc;
	Data data_wyslania;
};

#endif  //_WIADOMOSC_H
