//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wiadomosc.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_WIADOMOSC_H)
#define _WIADOMOSC_H

#include <string>
#include <memory>
#include <vector>
#include <fstream>
#include <nlohmann/json.hpp>
#include "Data.h"

using json = nlohmann::json;

class Uzytkownik;


class Wiadomosc {
private:
	std::string adresat;
	std::string nadawca;
	std::vector<std::string> tresc;
	Data data_wyslania;
	Wiadomosc();
	void dopisz_do_pliku();
public:
	Wiadomosc(std::string nadawca, std::string adresat, std::vector<std::string> tresc, Data data_wyslania);
	static std::vector<Wiadomosc> odczytaj_wiadomosci(std::string nazwa_uzytkownika);
	
};

#endif  //_WIADOMOSC_H
