//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WirtualnaRecepcja.cpp
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#include "WirtualnaRecepcja.h"

WirtualnaRecepcja::WirtualnaRecepcja() {}

std::shared_ptr<WirtualnaRecepcja> WirtualnaRecepcja::pobierzInstancje() {
    static std::shared_ptr<WirtualnaRecepcja> instancja(new WirtualnaRecepcja());
    return instancja;
}

void WirtualnaRecepcja::zamelduj(Rezerwacja rezerwacja) 
{

}

void WirtualnaRecepcja::wymelduj() 
{

}

