//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WirtualnaRecepcja.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_WIRTUALNARECEPCJA_H)
#define _WIRTUALNARECEPCJA_H

#include <vector>
#include "Rezerwacja.h"

class WirtualnaRecepcja {
private:
	std::vector<Rezerwacja> aktualni_goscie;
	std::vector<Pokoj> pokoje;
	void zamelduj(Rezerwacja rezerwacja);
	void wymelduj();
};

#endif  //_WIRTUALNARECEPCJA_H
