//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WirtualnaRecepcja.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_WIRTUALNARECEPCJA_H)
#define _WIRTUALNARECEPCJA_H

#include <vector>
#include "Rezerwacja.h"

class WirtualnaRecepcja {
private:
	WirtualnaRecepcja();
	WirtualnaRecepcja(const WirtualnaRecepcja&) = delete;
	WirtualnaRecepcja& operator=(const WirtualnaRecepcja&) = delete;

	std::vector<Rezerwacja> aktualni_goscie;
	std::vector<std::shared_ptr<Pokoj>> pokoje;
	void zamelduj(Rezerwacja rezerwacja);
	void wymelduj();
public:
	static std::shared_ptr<WirtualnaRecepcja> pobierzInstancje();
};

#endif  //_WIRTUALNARECEPCJA_H
