//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WirtualnaRecepcja.h
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#if !defined(_WIRTUALNARECEPCJA_H)
#define _WIRTUALNARECEPCJA_H

#include <vector>
#include "Ekran.h"
#include "Rezerwacja.h"
#include "Katalog.h"

class WirtualnaRecepcja {
private:
	WirtualnaRecepcja();
	WirtualnaRecepcja(const WirtualnaRecepcja&) = delete;
	WirtualnaRecepcja& operator=(const WirtualnaRecepcja&) = delete;

	std::vector<Rezerwacja> wszystkie_rezerwacje;
	std::vector<std::shared_ptr<Pokoj>> pokoje;

	void rezerwacje(std::vector<short> indeksy, int tryb = 0);


public:
	static std::shared_ptr<WirtualnaRecepcja> pobierzInstancje();
	void zamelduj();
	void wymelduj();
	void przegladaj_pokoje();
	void przegladaj_rezerwacje();
};

#endif  //_WIRTUALNARECEPCJA_H
