//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WirtualnaRecepcja.cpp
//  @ Date : 05.05.2025
//  @ Author : 
//
//


#include "WirtualnaRecepcja.h"
#include "Rezerwacja.h"

void WirtualnaRecepcja::zamelduj(Rezerwacja rezerwacja) {

}

void WirtualnaRecepcja::wymelduj() {

}

